apiVersion: v1
kind: Service
metadata:
  name: api-zabbix-agent   
spec:
  type: LoadBalancer
  selector:
    app: api                 
  ports:
    - name: agent
      protocol: TCP
      port: 10050           
      targetPort: 10050      
  type: ClusterIP
