apiVersion: v1
kind: Service
metadata:
  name: zabbix-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30002
  selector:
    app: zabbix
