version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - fase5_network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: sqlserver
    environment:
      SA_PASSWORD: "Fiap@2025"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - fase5_network

  api:
    build:
      context: .
      dockerfile: Fase5.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      RabbitMQ__Host: rabbitmq
      ConnectionStrings__Fase5Context: "Server=sqlserver,1433;Database=Fase5Db;User ID=sa;Password=Fiap@2025;TrustServerCertificate=True"
    depends_on:
      rabbitmq:
        condition: service_healthy
      sqlserver:
        condition: service_started
    networks:
      - fase5_network

  worker:
    build:
      context: .
      dockerfile: Fase5.Worker/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      RabbitMQ__Host: rabbitmq
      ConnectionStrings__Fase5Context: "Server=sqlserver,1433;Database=Fase5Db;User ID=sa;Password=Fiap@2025;TrustServerCertificate=True"
    depends_on:
      rabbitmq:
        condition: service_healthy
      sqlserver:
        condition: service_started
    networks:
      - fase5_network

networks:
  fase5_network:
    driver: bridge